name: project deploy

on:
  push:
    branches:
      - dev

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login
        run: git config --global user.email "lamphc@live.com" && git config --global user.name "lamphc"
      - name: Build
        run: npm install && npm run deploy
