name: project deploy

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.project-deploy }}
          BRANCH: gh-pages
          FOLDER: build
          BUILD_SCRIPT: npm install && npm run build
# jobs:
#   build-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Login
#         run: git config --global user.email "lamphc@live.com" && git config --global user.name "lamphc"
#       - name: Dkey
#         run: git remote set-url origin https://8c2888bc08a3fbdcda6b72e16cb75d3853109dba@github.com/lamphc/hkzf-mobile>.git
#       - name: Build
#         run: npm install && npm run deploy
