name: project deploy

on:
  push:
    branches:
      - dev

  jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@master

        - name: Build and Deploy
          uses: JamesIves/github-pages-deploy-action@master
          env:
            ACCESS_TOKEN: ${{ secrets.project-deploy }}
            BRANCH: gh-pages
            FOLDER: build
            BUILD_SCRIPT: npm install && npm run build
